-- MySQL Script generated by MySQL Workbench
-- Mon Apr 22 16:47:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projektor
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projektor` ;

-- -----------------------------------------------------
-- Schema projektor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projektor` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `projektor` ;

-- -----------------------------------------------------
-- Table `projektor`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`user` ;

CREATE TABLE IF NOT EXISTS `projektor`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `role` ENUM('client', 'provider', 'client_and_provider') NOT NULL,
  `postal_code` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `geo_loc` VARCHAR(60) NULL DEFAULT NULL,

  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projektor`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`account` ;

CREATE TABLE IF NOT EXISTS `projektor`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `iban` VARCHAR(34) NOT NULL,
  `bic` VARCHAR(11) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iban` (`iban` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `account_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `projektor`.`user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projektor`.`command`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`command` ;

CREATE TABLE IF NOT EXISTS `projektor`.`command` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projektor`.`jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`jobs` ;

CREATE TABLE IF NOT EXISTS `projektor`.`jobs` (
  `id` INT NOT NULL,
  `label` VARCHAR(45) NOT NULL COMMENT '\'plumbing\', \'masonry\', \'painting\', \'electricity\', \'roofing\', \'locksmith\', \'cleaning\', \'landscaping\'',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projektor`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`project` ;

CREATE TABLE IF NOT EXISTS `projektor`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `deadline` DATE NOT NULL,
  `priority` INT NOT NULL,
  `status` ENUM('in progress', 'completed') NOT NULL DEFAULT 'in progress',
  `author` INT NOT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user` (`author` ASC) VISIBLE,
  CONSTRAINT `project_ibfk_1`
    FOREIGN KEY (`author`)
    REFERENCES `projektor`.`user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projektor`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`task` ;

CREATE TABLE IF NOT EXISTS `projektor`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `deadline` DATE NOT NULL,
  `priority` INT NOT NULL,
  `status` ENUM('in_progress', 'start', 'postponed', 'completed') NOT NULL DEFAULT 'start',
  `id_project` INT NOT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  `jobs_id` INT NOT NULL,
  `postal_code` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `geo_loc` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_project` (`id_project` ASC) VISIBLE,
  INDEX `fk_task_jobs1_idx` (`jobs_id` ASC) VISIBLE,
  CONSTRAINT `fk_task_jobs1`
    FOREIGN KEY (`jobs_id`)
    REFERENCES `projektor`.`jobs` (`id`),
  CONSTRAINT `task_ibfk_1`
    FOREIGN KEY (`id_project`)
    REFERENCES `projektor`.`project` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projektor`.`quote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`quote` ;

CREATE TABLE IF NOT EXISTS `projektor`.`quote` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `supposed_start_date` DATETIME NOT NULL,
  `supposed_end_date` DATETIME NULL DEFAULT NULL,
  `provider` INT NOT NULL,
  `task` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user` (`provider` ASC) VISIBLE,
  INDEX `fk_quote_task1_idx` (`task` ASC) VISIBLE,
  CONSTRAINT `fk_quote_task1`
    FOREIGN KEY (`task`)
    REFERENCES `projektor`.`task` (`id`),
  CONSTRAINT `quote_ibfk_1`
    FOREIGN KEY (`provider`)
    REFERENCES `projektor`.`user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projektor`.`command_has_quote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`command_has_quote` ;

CREATE TABLE IF NOT EXISTS `projektor`.`command_has_quote` (
  `command_id` INT NOT NULL,
  `quote_id` INT NOT NULL,
  PRIMARY KEY (`command_id`, `quote_id`),
  INDEX `fk_command_has_quote_quote1_idx` (`quote_id` ASC) VISIBLE,
  INDEX `fk_command_has_quote_command1_idx` (`command_id` ASC) VISIBLE,
  CONSTRAINT `fk_command_has_quote_command1`
    FOREIGN KEY (`command_id`)
    REFERENCES `projektor`.`command` (`id`),
  CONSTRAINT `fk_command_has_quote_quote1`
    FOREIGN KEY (`quote_id`)
    REFERENCES `projektor`.`quote` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projektor`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`message` ;

CREATE TABLE IF NOT EXISTS `projektor`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT NOT NULL,
  `date_added` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_task` INT NOT NULL,
  `author` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_task` (`id_task` ASC) VISIBLE,
  INDEX `fk_message_user1_idx` (`author` ASC) VISIBLE,
  CONSTRAINT `fk_message_user1`
    FOREIGN KEY (`author`)
    REFERENCES `projektor`.`user` (`id`),
  CONSTRAINT `message_ibfk_1`
    FOREIGN KEY (`id_task`)
    REFERENCES `projektor`.`task` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projektor`.`photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`photo` ;

CREATE TABLE IF NOT EXISTS `projektor`.`photo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `author` INT NOT NULL,
  `content` BLOB NULL DEFAULT NULL,
  `task_id` INT NULL DEFAULT NULL,
  `project_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user` (`author` ASC) VISIBLE,
  INDEX `fk_photo_task1_idx` (`task_id` ASC) VISIBLE,
  INDEX `fk_photo_project1_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_photo_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_photo_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `projektor`.`project` (`id`),
  CONSTRAINT `fk_photo_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `projektor`.`task` (`id`),
  CONSTRAINT `fk_photo_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `projektor`.`user` (`id`),
  CONSTRAINT `photo_ibfk_1`
    FOREIGN KEY (`author`)
    REFERENCES `projektor`.`user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projektor`.`provider_has_jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`provider_has_jobs` ;

CREATE TABLE IF NOT EXISTS `projektor`.`provider_has_jobs` (
  `user_id` INT NOT NULL,
  `jobs_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `jobs_id`),
  INDEX `fk_user_has_jobs_jobs1_idx` (`jobs_id` ASC) VISIBLE,
  INDEX `fk_user_has_jobs_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_jobs_jobs1`
    FOREIGN KEY (`jobs_id`)
    REFERENCES `projektor`.`jobs` (`id`),
  CONSTRAINT `fk_user_has_jobs_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `projektor`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projektor`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`review` ;

CREATE TABLE IF NOT EXISTS `projektor`.`review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rating` INT NOT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `client` INT NOT NULL,
  `provider` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user` (`client` ASC) VISIBLE,
  INDEX `fk_review_user1_idx` (`provider` ASC) VISIBLE,
  CONSTRAINT `fk_review_user1`
    FOREIGN KEY (`provider`)
    REFERENCES `projektor`.`user` (`id`),
  CONSTRAINT `review_ibfk_1`
    FOREIGN KEY (`client`)
    REFERENCES `projektor`.`user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



-- |||||||  generating the seed ||||||||| --

-- Inserting Pokémon (users) data
INSERT INTO projektor.user (password, first_name, last_name, email, phone, role) VALUES
                                                                                             ('$2a$10$dUGekC7WsVaa2QmYegSNp.X2Da.Jgl6L4nATaIaEF2qRMdl.qox2.', 'Pikachu', 'xxx', 'pikachu@example.com', '12345677', 'client'),
                                                                                             ('$2a$10$dUGekC7WsVaa2QmYegSNp.X2Da.Jgl6L4nATaIaEF2qRMdl.qox2.', 'Bulbasaur', 'wxcwxc', 'bulbasaur@example.com', '12345677', 'client'),
                                                                                             ('$2a$10$dUGekC7WsVaa2QmYegSNp.X2Da.Jgl6L4nATaIaEF2qRMdl.qox2.', 'Charmander', 'wwxcw', 'charmander@example.com', '12345677', 'client'),
                                                                                             ('$2a$10$dUGekC7WsVaa2QmYegSNp.X2Da.Jgl6L4nATaIaEF2qRMdl.qox2.', 'Squirtle', 'wxcwxc', 'squirtle@example.com', '12345677', 'client'),
                                                                                             ('$2a$10$dUGekC7WsVaa2QmYegSNp.X2Da.Jgl6L4nATaIaEF2qRMdl.qox2.', 'Jigglypuff', 'sdzfsdf', 'jigglypuff@example.com', '12345677', 'client'),
                                                                                            ('$2a$10$dUGekC7WsVaa2QmYegSNp.X2Da.Jgl6L4nATaIaEF2qRMdl.qox2.', 'Tony', 'Stark', 'tony@example.com', '123456789', 'client'),
                                                                                            ('$2a$10$dUGekC7WsVaa2QmYegSNp.X2Da.Jgl6L4nATaIaEF2qRMdl.qox2.', 'Stephen', 'Strange', 'stephen@example.com', '987654321', 'provider'),
                                                                                            ('$2a$10$dUGekC7WsVaa2QmYegSNp.X2Da.Jgl6L4nATaIaEF2qRMdl.qox2.', 'Reed', 'Richards','reed@example.com', '111222333', 'client_and_provider'),
                                                                                            ('$2a$10$dUGekC7WsVaa2QmYegSNp.X2Da.Jgl6L4nATaIaEF2qRMdl.qox2.', 'Peter', 'Parker', 'peter@example.com', '333444555', 'provider'),
                                                                                            ('$2a$10$dUGekC7WsVaa2QmYegSNp.X2Da.Jgl6L4nATaIaEF2qRMdl.qox2.', 'Bruce', 'Banner', 'bruce@example.com', '666777888', 'provider');

-- Optional: If you need to assign provider roles to some users
-- You can execute an UPDATE query to modify the appropriate role

-- Example: Update Bulbasaur's role to provider
-- UPDATE projektor.user SET role = 'provider' WHERE first_name = 'Bulbasaur';

-- If you need to enter additional information for each user, you can expand the inserted data





-- Inserting seed data for the account table
INSERT INTO projektor.account (name, iban, bic, user_id)
VALUES
    ('Account 1', 'DE89370400440532013000', 'COBADEFFXXX', 1),
    ('Account 2', 'FR1420041010050500013M02606', 'BNPAFRPPXXX', 2),
    ('Account 3', 'GB33BUKB20201555555555', 'BARCGB22XXX', 3);

-- Inserting seed data for other tables follows a similar pattern


-- Inserting Reviews
    INSERT INTO projektor.review (rating, comment, date_added, client, provider)
VALUES
    (5, 'Excellent service! Would highly recommend.', NOW(), 1, 2),
    (4, 'Great job, but could be improved.', NOW(), 3, 4),
    (4, 'Great work on the plumbing repairs!', '2024-05-02 12:00:00', 1, 2), -- Review by Pikachu (user_id: 1) for Brock (user_id: 2)
    (5, 'Excellent service and craftsmanship!', '2024-05-07 10:30:00', 3, 3), -- Review by Ash (user_id: 3) for Misty (user_id: 3)
    (3, 'Satisfactory job, but could be better.', '2024-05-10 14:45:00', 4, 4), -- Review by Squirtle (user_id: 4) for Peter Parker (user_id: 4)
    (5, 'Highly recommended! Professional and efficient.', '2024-05-15 11:20:00', 5, 5), -- Review by Jigglypuff (user_id: 5) for Jigglypuff (user_id: 5)
    (4, 'Good communication and quality work.', '2024-05-20 09:30:00', 2, 6); -- Review by Bulbasaur (user_id: 2) for Bruce Banner (user_id: 6)

-- Inserting Projects
    INSERT INTO projektor.project (title, description, deadline, priority, status, author, start_date, end_date)
VALUES
    ('Repairing Tony Stark\'s house', 'Repairing Tony Stark\'s house', '2024-05-01', 1, 'in progress', 1, NOW(), NULL),
    ('Renovating Dr. Strange\'s manor', 'Renovating Dr. Strange\'s manor', '2024-05-15', 2, 'in progress', 2, NOW(), NULL),
    ('Repairing Tony Stark\'s house', 'Repairing damages caused by recent attacks.', '2024-05-01', 1, 'in progress', 1, NOW(), NULL),
    ('Renovating Dr. Strange\'s manor', 'Restoration and magical enhancements.', '2024-05-15', 2, 'in progress', 2, NOW(), NULL),
    ('Stark Tower Energy Upgrade', 'Implementing clean energy solutions.', '2024-05-20', 3, 'in progress', 1, NOW(), NULL),
    ('Avengers Headquarters Expansion', 'Adding new facilities for training and operations.', '2024-06-10', 4, 'in progress', 1, NOW(), NULL),
    ('Baxter Building Renovation', 'Modernizing infrastructure and research labs.', '2024-06-30', 5, 'in progress', 3, NOW(), NULL);

-- Populating the Quote Table with Sample Data
-- TODO Ajouter des Jobs
-- TODO Ajouter des task
-- TODO Ajouter les quote
-- INSERT INTO projektor.quote (description, price, supposed_start_date, supposed_end_date, provider, task)
-- VALUES
--    ('Replacement of damaged pipes', 1500.00, '2024-04-25 08:00:00', '2024-05-01 18:00:00', 2, 1), -- Quote provided by Brock (user_id: 2) for Task 1
--    ('Interior painting of living room', 800.00, '2024-04-30 09:00:00', '2024-05-07 17:00:00', 3, 2), -- Quote provided by Misty (user_id: 3) for Task 2
--    ('Roof repair and maintenance', 2500.00, '2024-05-03 08:00:00', '2024-05-10 18:00:00', 4, 3), -- Quote provided by Peter Parker (user_id: 4) for Task 3
--    ('Garden landscaping and design', 1200.00, '2024-05-05 10:00:00', '2024-05-12 16:00:00', 5, 4), -- Quote provided by Jigglypuff (user_id: 5) for Task 4
--    ('Electrical wiring installation', 1800.00, '2024-05-08 08:00:00', '2024-05-15 18:00:00', 6, 5); -- Quote provided by Peter Parker (user_id: 6) for Task 5


-- Assigning Jobs to Providers
-- INSERT INTO projektor.provider_has_jobs (user_id, jobs_id)
-- VALUES
--   (6, 1), -- Peter Parker for Plumbing
--    (7, 2), -- Bruce Banner for Masonry
--    (8, 3); -- [Insert User ID] for [Insert Job ID]

-- Populating the Message Table with Sample Data
-- INSERT INTO projektor.message (text, date_added, id_task, author)
-- VALUES
--    ('Please confirm the materials required for the project.', NOW(), 1, 1), -- Sent by Pikachu (user_id: 1) for Task 1
--    ('Sure, I will provide the list by tomorrow.', NOW(), 1, 2), -- Sent by Bulbasaur (user_id: 2) for Task 1
--    ('We need additional assistance for plumbing work.', NOW(), 2, 3), -- Sent by Ash (user_id: 3) for Task 2
--    ('Please confirm the schedule for the project.', NOW(), 5, 4), -- Sent by Tony Stark (user_id: 4) for Task 5
--    ('The schedule is confirmed. We will start on Monday.', NOW(), 5, 4); -- Sent by Tony Stark (user_id: 4) for Task 5


-- Populating the Command Table
-- INSERT INTO projektor.command (id)
-- VALUES
--    (1),
--    (2),
--    (3),
--    (4),
--    (5);

-- Populating the Photo Table with Sample Data
-- INSERT INTO projektor.photo (description, date_added, author, content, task_id, project_id, user_id)
-- VALUES
--    ('Photo of completed plumbing work', NOW(), 1, 'binary_data_here', NULL, NULL, 2), -- Photo uploaded by Bulbasaur (user_id: 2)
--    ('Photo of painting progress', NOW(), 3, 'binary_data_here', 1, NULL, 3), -- Photo uploaded by Charmander (user_id: 3) for Task 1
--    ('Photo of roofing materials', NOW(), 5, 'binary_data_here', NULL, 3, 5), -- Photo uploaded by Jigglypuff (user_id: 5) for Project 3
--    ('Photo of landscaping design', NOW(), 2, 'binary_data_here', NULL, NULL, 1), -- Photo uploaded by Pikachu (user_id: 1)
--    ('Photo of electrical wiring', NOW(), 4, 'binary_data_here', 2, NULL, 4); -- Photo uploaded by Squirtle (user_id: 4) for Task 2


-- FIN DU SCRIPT --
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


