-- MySQL Script generated by MySQL Workbench
-- Mon Apr 22 16:47:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projektor
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projektor` ;

-- -----------------------------------------------------
-- Schema projektor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projektor` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `projektor` ;

-- -----------------------------------------------------
-- Table `projektor`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`user` ;

CREATE TABLE IF NOT EXISTS `projektor`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `role` ENUM('client', 'provider', 'client_and_provider') NOT NULL,
  `postal_code` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `geo_loc` VARCHAR(60) NULL DEFAULT NULL,
  `usercol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projektor`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`account` ;

CREATE TABLE IF NOT EXISTS `projektor`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `iban` VARCHAR(34) NOT NULL,
  `bic` VARCHAR(11) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iban` (`iban` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `account_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `projektor`.`user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projektor`.`command`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`command` ;

CREATE TABLE IF NOT EXISTS `projektor`.`command` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projektor`.`jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`jobs` ;

CREATE TABLE IF NOT EXISTS `projektor`.`jobs` (
  `id` INT NOT NULL,
  `label` VARCHAR(45) NOT NULL COMMENT '\'plumbing\', \'masonry\', \'painting\', \'electricity\', \'roofing\', \'locksmith\', \'cleaning\', \'landscaping\'',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projektor`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`project` ;

CREATE TABLE IF NOT EXISTS `projektor`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL DEFAULT NULL,
  `deadline` DATE NOT NULL,
  `priority` INT NOT NULL,
  `status` ENUM('in progress', 'completed') NOT NULL DEFAULT 'in progress',
  `author` INT NOT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user` (`author` ASC) VISIBLE,
  CONSTRAINT `project_ibfk_1`
    FOREIGN KEY (`author`)
    REFERENCES `projektor`.`user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projektor`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`task` ;

CREATE TABLE IF NOT EXISTS `projektor`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `deadline` DATE NOT NULL,
  `priority` INT NOT NULL,
  `status` ENUM('in_progress', 'start', 'postponed', 'completed') NOT NULL DEFAULT 'start',
  `id_project` INT NOT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  `jobs_id` INT NOT NULL,
  `postal_code` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `geo_loc` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_project` (`id_project` ASC) VISIBLE,
  INDEX `fk_task_jobs1_idx` (`jobs_id` ASC) VISIBLE,
  CONSTRAINT `fk_task_jobs1`
    FOREIGN KEY (`jobs_id`)
    REFERENCES `projektor`.`jobs` (`id`),
  CONSTRAINT `task_ibfk_1`
    FOREIGN KEY (`id_project`)
    REFERENCES `projektor`.`project` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projektor`.`quote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`quote` ;

CREATE TABLE IF NOT EXISTS `projektor`.`quote` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `supposed_start_date` DATETIME NOT NULL,
  `supposed_end_date` DATETIME NULL DEFAULT NULL,
  `provider` INT NOT NULL,
  `task` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user` (`provider` ASC) VISIBLE,
  INDEX `fk_quote_task1_idx` (`task` ASC) VISIBLE,
  CONSTRAINT `fk_quote_task1`
    FOREIGN KEY (`task`)
    REFERENCES `projektor`.`task` (`id`),
  CONSTRAINT `quote_ibfk_1`
    FOREIGN KEY (`provider`)
    REFERENCES `projektor`.`user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projektor`.`command_has_quote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`command_has_quote` ;

CREATE TABLE IF NOT EXISTS `projektor`.`command_has_quote` (
  `command_id` INT NOT NULL,
  `quote_id` INT NOT NULL,
  PRIMARY KEY (`command_id`, `quote_id`),
  INDEX `fk_command_has_quote_quote1_idx` (`quote_id` ASC) VISIBLE,
  INDEX `fk_command_has_quote_command1_idx` (`command_id` ASC) VISIBLE,
  CONSTRAINT `fk_command_has_quote_command1`
    FOREIGN KEY (`command_id`)
    REFERENCES `projektor`.`command` (`id`),
  CONSTRAINT `fk_command_has_quote_quote1`
    FOREIGN KEY (`quote_id`)
    REFERENCES `projektor`.`quote` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projektor`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`message` ;

CREATE TABLE IF NOT EXISTS `projektor`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT NOT NULL,
  `date_added` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_task` INT NOT NULL,
  `author` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_task` (`id_task` ASC) VISIBLE,
  INDEX `fk_message_user1_idx` (`author` ASC) VISIBLE,
  CONSTRAINT `fk_message_user1`
    FOREIGN KEY (`author`)
    REFERENCES `projektor`.`user` (`id`),
  CONSTRAINT `message_ibfk_1`
    FOREIGN KEY (`id_task`)
    REFERENCES `projektor`.`task` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projektor`.`photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`photo` ;

CREATE TABLE IF NOT EXISTS `projektor`.`photo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `author` INT NOT NULL,
  `content` BLOB NULL DEFAULT NULL,
  `task_id` INT NULL DEFAULT NULL,
  `project_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user` (`author` ASC) VISIBLE,
  INDEX `fk_photo_task1_idx` (`task_id` ASC) VISIBLE,
  INDEX `fk_photo_project1_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_photo_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_photo_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `projektor`.`project` (`id`),
  CONSTRAINT `fk_photo_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `projektor`.`task` (`id`),
  CONSTRAINT `fk_photo_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `projektor`.`user` (`id`),
  CONSTRAINT `photo_ibfk_1`
    FOREIGN KEY (`author`)
    REFERENCES `projektor`.`user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projektor`.`provider_has_jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`provider_has_jobs` ;

CREATE TABLE IF NOT EXISTS `projektor`.`provider_has_jobs` (
  `user_id` INT NOT NULL,
  `jobs_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `jobs_id`),
  INDEX `fk_user_has_jobs_jobs1_idx` (`jobs_id` ASC) VISIBLE,
  INDEX `fk_user_has_jobs_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_jobs_jobs1`
    FOREIGN KEY (`jobs_id`)
    REFERENCES `projektor`.`jobs` (`id`),
  CONSTRAINT `fk_user_has_jobs_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `projektor`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projektor`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projektor`.`review` ;

CREATE TABLE IF NOT EXISTS `projektor`.`review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rating` INT NOT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `date_added` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `client` INT NOT NULL,
  `provider` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user` (`client` ASC) VISIBLE,
  INDEX `fk_review_user1_idx` (`provider` ASC) VISIBLE,
  CONSTRAINT `fk_review_user1`
    FOREIGN KEY (`provider`)
    REFERENCES `projektor`.`user` (`id`),
  CONSTRAINT `review_ibfk_1`
    FOREIGN KEY (`client`)
    REFERENCES `projektor`.`user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
